baseURL: https://julienlavocat.github.io
languageCode: en-us
title: Julien Lavocat
theme: PaperMod

enableEmoji: true

params:
  profileMode:
    enabled: true
    title: "Julien Lavocat"
    subtitle: "Fullstack software engineer"
    imageUrl: "./profile.webp"
    imageTitle: "A picture of me"
    imageWidth: 240
    imageHeight: 240
    buttons:
      - name: About Me
        url: "/about-me"
      - name: Blog
        url: "/posts"

  socialIcons: # optional
    - name: github
      url: "https://github.com/JulienLavocat"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/julienlavocat/"
    - name: "medium"
      url: "https://medium.com/@julienlavocat"

  ShowReadingTime: true
  ShowTOC: true

  comments: true

menu:
  main:
    - identifier: about
      name: About Me
      url: about-me
      weight: 10
    - identifier: blog
      name: Blog
      url: posts
      weight: 20
    - identifier: projects
      name: Projects
      url: projects
      weight: 30
    - identifier: work
      name: Work
      url: work
      weight: 40
